### ISSUE TITLE
Go_router "books" example adaptation to riverpod problems

### ISSUE THREAD

**Issue by Josua2012** [rrousselGit/river_pod#1128]
Hi,
I have tried to modify the go_router "books" example to adapt it to riverpod, but I have had many problems and errors, it seems that there are bugs in riverpod.
How could BookstoreAuthScope and BookstoreAuth be adapted? 
Thanks for the help. 
Regards,

**Comment by rrousselGit** [comment]
There is no official go_router example. What you're talking about is most likely a community-maintained example, which I am not responsible for.

I'd suggest raising an issue on the repository of that example instead, as there is nothing I can do.

**Comment by jamolina2021** [comment]
Hi @rrousselGit,

The "books" example is inside the examples folder on github of the go_router library, I assume it will be an official example.
https://github.com/csells/go_router/tree/main/go_router/example/lib/books

The problem is not in the "books" example, nor in go_router, everything works perfectly, the problem is when you try to use riverpod to do the initial management instead of the method they use there. 

For that reason I was asking you, because you are the developer of riverpod, and I suppose you want it to work perfectly together with one of the navigation libraries that are currently being used the most. 

Regards,
Jose

**Comment by rrousselGit** [comment]
Oh. Then there's already an issue asking for a go_router example. So you'll have to wait

**Comment by jamolina2021** [comment]
Ok. Thanks @rrousselGit.
