### ISSUE TITLE
What are cases I've to use ref.read(provider) instead of ref.watch(provider.notifier)?

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/river_pod#1247]
I'm currently using ref.watch(provider.notifier) in my projects as it's recommend over ref.read, even with state providers I'm using ref.watch(provider.notifier).state.

Everything works fine but when I've to use ref.read or why it's exist?
Also, Is it ok to use ref.watch(provider.notifier) in State life-cycles & onPressed?

**Comment by lucavenir** [comment]
From my understanding, `ref.read` is meant to be used to perform a single read of a Provider's current value. This is why it is so useful when used to read a notifier, in which you probably want to access its methods, rather than actively watching or listening for changes. Another good use of `ref.read` is inside buttons' callbacks (or anything similar).

Other than that, ref.read is dangerous to use since you'll probably incur into unexpected bugs. You most likely want to watch or listen to a provider to react to its changes.

**Comment by AhmedLSayed9** [comment]
ref.watch(provider.notifier) doesn't listen for changes too and it's recommended over ref.read, that's the reason for my questions above.

**Comment by lucavenir** [comment]
In that comment the maintainer said what I say above: don't use `read` on providers. Use `watch` instead. But you were asking about using `ref.read` on notifiers like `ref.read(provider.notifier)`, which is different.

My comment is a summary of this [doc page](https://riverpod.dev/docs/concepts/reading/#using-refread-to-obtain-the-state-of-a-provider), where you can clearly see where to use `read` and where to use `watch`.

Hope this helps

**Comment by AhmedLSayed9** [comment]
![image](https://user-images.githubusercontent.com/70890146/156408783-5113374d-b121-49c3-bae1-900f3c911e9b.PNG)

**Comment by lucavenir** [comment]
From my understanding, when we got into Riverpod `1.0` all `StateNotifier` got an uniformed API. Before that, i.e. in `0.x` versions, `StateProvider` and `StateNotifierProvider` behaved differently when it came to reading state. Maybe the inline documentation is to be updated, I'm not sure.

As for that comment, from my understanding it clearly refers to `StateNotifer` because of the `ref.read(provider.notifier)` practice.

**Comment by rrousselGit** [comment]
> ref.watch(provider.notifier) doesn't listen for changes too and it's recommended over ref.read, that's the reason for my questions above.

It does somehow. As explained in the doc, if the Notifier is rebuilt (such as when using `ref.watch`/`ref.refresh`), then `watch(provider.notifier)` would rebuild the widget

**Comment by rrousselGit** [comment]
Using watch also prevents autoDispose provider from randomly getting disposed because they aren't listened

**Comment by rrousselGit** [comment]
Overall I'd refer to the watch vs read doc https://riverpod.dev/docs/concepts/reading/

**Comment by AhmedLSayed9** [comment]
Thanks Remi and sorry to bother but are these good practices?
1. Using ref.watch(provider.notifier) inside onPressed:
![cc](https://user-images.githubusercontent.com/70890146/156929561-04383a02-7349-4bb1-9307-29d214668839.PNG)
2. Using ref.watch(provider.notifier) or ref.watch("Basic Provider Type") inside initState:
![223](https://user-images.githubusercontent.com/70890146/156929566-457a1973-1db9-4e01-8eeb-0be1895226df.PNG)
