### ISSUE TITLE
Watching value only from context

### ISSUE THREAD

**Issue by davidmartos96** [rrousselGit/river_pod#134]
I was exploring the possibility of adding riverpod to some parts of my existing project which uses provider at the moment.
One of my current providers from the provider package is the theme of the app with custom colors and such.

From any of my widgets I can do `Provider.of<MyTheme>(context)`. I was wondering if there is a way of watching a specific riverpod provider by its name, without relying on `Consumer` or `ConsumerWidget`.

Something along the lines of:
```dart
static MyTheme of(BuildContext context){
  return  ProviderScope.containerOf(context).watch(_myThemeProvider);
}
``` 

I find migrating my current MyTheme dependency to riverpod very hard or nearly impossible if using `Consumer/ConsumerWidget/useProvider` is the only solution because many of my widgets depend on the signature from above. 

Migrating to using Consumers can be doable but not for moderately sized projects.

**Comment by rrousselGit** [comment]
This is not feasible and is in fact one of the reasons why Riverpod and Provider are separated.

This would both significantly reduce the performances and remove some features (like ".autoDispose")

The question would instead be:

Why is it hard for you to migrate to Consumer/ConsumerWidget/useProvider?

**Comment by davidmartos96** [comment]
I totally understand if this is not feasible at all to do. I just wanted to share my experience from an existent Provider project standpoint.

> The question would instead be:
> 
> Why is it hard for you to migrate to Consumer/ConsumerWidget/useProvider?

Simply put:
* Big project with many different widgets. Error prone to update all that code.

**Comment by rrousselGit** [comment]
> Big project with many different widgets. Error prone to update all that code.

How so? 
You'd have a compile error if you made a mistake

**Comment by davidmartos96** [comment]
I guess that's true thanks to the compile safety from riverpod.

**Comment by porfirioribeiro** [comment]
In some situations it's not so linear.

If you have StatefullWidget's where you mix `setState` and `Provider` it's a little bit harder to just migrate to ConsumerWidget or Consumer

In my case, when i had just a simple inner state, i converted to a `ConsumerWidget` and created a private `StateProvider` and used it instead of `setState`. In other cases where that provider state could be used in isolation, i just used a `Consumer` widget.

But i ended up being able to migrate our App to river_pod, replacing `Provider` and `get_it` with it! Thanks allot for your work on all of this, by the way!

**Comment by davidmartos96** [comment]
@porfirioribeiro Couldn't you just turn your StatefulWidget into a ConsumerWidget? I think you could still use setState because ConsumerWidget extends from StatefulWidget :sweat_smile:

**Comment by rrousselGit** [comment]
> In some situations it's not so linear.

Could you give examples of those situations? One long-term plan is to make a script to automatically convert from provider to riverpod, so that would be really helpful

**Comment by rrousselGit** [comment]
Also, in the short term, I want to release a migration guide. "Riverpod for Provider users" or something like that

So if you could list your pain points, I'll make sure to cover them

**Comment by porfirioribeiro** [comment]
> > In some situations it's not so linear.
> 
> Could you give examples of those situations? One long-term plan is to make a script to automatically convert from provider to riverpod, so that would be really helpful

Well, `provider` can be injected in any widget type, so you could access it either on `StatelessWidget` or `StatefulWidget` 
For `river_pod` you need to change your widget either to `ConsumerWidget`/`HooksWidget` or wrap it in a `Consumer`

When using StatelessWidget was really straightforward to migrate to ConsumerWidget, (i didn't want to also bring `flutter_hooks` to the project, maybe later, need to investigate it more )

Now when you have a SatefulWidget because of some setState or some controllers its a little more complicated.
@davidmartos96  Even tho ConsumerWidget extends StatefulWidget you are extending the Widget not the State, so it does not work as a StatefulWidget, in my understanding.

**Comment by davidmartos96** [comment]
@porfirioribeiro Oh you are totally right.

**Comment by rrousselGit** [comment]
Could you expand on the difficulties encountered with StatefulWidget?

**Comment by esDotDev** [comment]
I think the issue stems from the docs not really every explaining how to use this with a Stateful Widget.

If I understand right, this is functionally equivalent to a ConsumerWidget??
```
class _MyWidgetState extends State<MyWidget> {
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, watch, _) {
          bool value = watch(myModel).value;
          return ...; 
      }
    )
  }
}
```
If that's true, then migrating from Provider shouldn't be tooo hard. 

The two main issue here are 
1. The nesting is unfortunate, at least it's only one level because one `watch()` method can presumably be used on multiple providers. But still, lots of lines, spaces and brackets compared to `context.watch`
2. Lack of a Select API renders this extremely unoptimized for architectures that prefer to have complex changeNotifiers as their provided dependencies.

In general I just find it very odd that we have a `context.read` for button handlers, but then can't have `context.watch` or `context.select` inside a stateful widget.

I also still don't full understand how we're supposed to access a provider from outside the widget tree completely, for instance if we want to implement our Application Logic using simple Command objects.

There's just so much going on, and so many options, and so many flavors it just makes it really hard to see the clear path forward when learning riverpod.

**Comment by lohanidamodar** [comment]
@esDotDev Yes accessing provider from outside widget tree using the Container is not clear to me either, and there is not much on the docs regarding that.
cc @rrousselGit

**Comment by AlexHartford** [comment]
Using flutter_hooks, even if only for hooks_riverpod, will really simplify the process of using riverpod for many users. It eliminates the nesting among other pain points that seem to be coming up with adopting riverpod.

There is `StatefulHookWidget` for those who really want to maintain verbose syntax using `StatefulWidget` for their state while gaining simpler usage of riverpod.  Then, when you are ready to embrace concise state management, it would be possible to remove `Stateful` widget by widget as you convert the remaining state to use hooks.

**Comment by esDotDev** [comment]
The argument isn't that switching over to a fully hooks-based approach is not going to simplify usage, it's that it greatly complicated understanding required before usage can occur. Assuming you're someone who likes to understand how code works, and why you're extending the classes you're extending.

First should be clear demonstrations of the 'un-simplified' process, so riverpod can be evaluated on it's own terms, using some common workflows. And then, if examples are provided of accelerators using additional libs, that would be great.

**Comment by AlexHartford** [comment]
Fair enough, I would still stand by the point that many if not all concerns I've seen are solved by using hooks though. Yes, more examples of non-hooks riverpod would be great, but it's definitely a case of stepping backwards to move forwards.

It seems more to me like a Flutter problem than a riverpod/hooks problem. The copious boilerplate required by vanilla Flutter (that vanilla riverpod is directly affected by) is all solved when using the simpler, more concise, hooks approach to building widgets. There are also really complex architectures that are being popularized for whatever reason that get people confused when working with riverpod/provider as well.

All that said, I'm sure everyone would welcome a contribution of an example using riverpod without hooks.

**Comment by rrousselGit** [comment]
Tutorials will be available in due time (not just examples, but code with the explanation)
I'll make sure that all the tutorials I write will be available both with and without hooks. Not just so that people can start slowly, but also compare approaches.

I probably won't be using `ChangeNotifier` though, and focus on `StateNotifier` + Freezed, and instead will make a single "ChangeNotifier vs StateNotifier" article

**Comment by davidmartos96** [comment]
@rrousselGit Would it be feasible to implement a custom hook called `useWatch`? It would return a `ScopedReader`, same as `ConsumerWidget`. That would make migrating `StatefulWidgets` easier with the help of `StatefulHookWidget` + avoiding unnecessary nesting in the process as @esDotDev mentioned previously.

**Comment by rrousselGit** [comment]
What would be the benefit over useProvider?

**Comment by davidmartos96** [comment]
Oh, nevermind. I wasn't thinking about `useProvider`. That could be used as well.

**Comment by rrousselGit** [comment]
Closing as there are no plans to implement this.

**Comment by passsy** [comment]
I really dislike the nesting `Consumer` creates. I remember that not having a `Consumer` widget was largely celebrated by everyone when extensions landed in Dart and `context.watch` was introduced to Provider. That's why I don't understand that this issue got dismissed, without a proper technical explanation.

> This would both significantly reduce the performances and remove some features (like ".autoDispose")

Can you elaborate on that? If performance isn't critical to me and I don't use `.autoDispose` at all, why can't I get `context.watch`?

**Comment by rrousselGit** [comment]
`ConsumerWidget` exists for this purpose.

It removes the nesting but doesn't rely on InheritedWidget's subscription mechanism.

**Comment by rrousselGit** [comment]
> Can you elaborate on that? If performance isn't critical to me and I don't use `.autoDispose` at all, why can't I get `context.watch`?

InheritedWidgets work by keeping track of all the dependent widgets bound to one InheritedWidget. 
They need to be inserted in the widget tree beforehand for consumers to depend on it, and we typically have one inherited widget per state.

Riverpod is different. The providers are not present in the widget tree until the moment that we read them. And we don't have one "InheritedWidget" per provider, but rather one for **all** providers.

So trying to fit providers in the InheritedWidget model requires heavy workarounds.
Everytime we would like a provider to emit an update, we would have to iterate over **all** providers and **all** consumers (including those that called `context.watch` for a different provider). This simply doesn't scale.

By relying on `ConsumerWidget`, when a provider wants to emit an update, we evaluate only that provider and iterate over only its consumers.

Considering `ConsumerWidget` solves this problem with pretty much no downside, while also being more future-proof (with autoDispose and more to come), I don't see a reason to maintain two different approaches.

**Comment by rrousselGit** [comment]
`autoDispose` is also not the only feature that requires `ConsumerWidget`.

There are more to come. Such as:

- the ability to have "gapless playback" for `AsyncValue` (as in, after the first data, going back to loading keeps showing the data).
- enabling the devtool to list all the consumers associated with a provider
- supporting an "onChange" that doesn't require nesting:
  ```dart
  Widget build(context, ref) {
    ref.listen<Value>(provider, (value) => showDialog(...));
  }
  ```



Using `ConsumerWidget` also fixes bugs in InheritedWidgets. Such as https://github.com/flutter/flutter/issues/62753 and https://github.com/flutter/flutter/issues/62861

**Comment by passsy** [comment]
> Riverpod is different. The providers are not present in the widget tree until the moment that we read them. And we don't have one "InheritedWidget" per provider, but rather one for **all** providers.
>
> Everytime we would like a provider to emit an update, we would have to iterate over **all** providers and **all** consumers (including those that called `context.watch` for a different provider). This simply doesn't scale.

That was the missing link, thanks!

**Comment by realshovanshah** [comment]
> Could you give examples of those situations? One long-term plan is to make a script to automatically convert from provider to riverpod, so that would be really helpful

Hey @rrousselGit, do we still have this in our roadmap?

**Comment by rrousselGit** [comment]
Yes, I still want to make a script to convert from provider to Riverpod.

Although it's a lot of work and there are more valuable things to work on atm (docs, devtools)
