### ISSUE TITLE
`ref.invalidate` should trigger `loading()` of `AsyncValue`, introduce `AsyncValue.refreshing()`

### ISSUE THREAD

**Issue by krjw-eyev** [rrousselGit/river_pod#1568]
**Is your feature request related to a problem? Please describe.**
I'm new to riverpod and may not have it all figured out yet, but I've come across 2 scenarios where I see room for improvement: 

1. I am using `FutureProvider` to load data and if I want to update the view I call `ref.refresh` on my providers future. I know that `isRefreshing` indicates that state but I would like to make the refreshing visible in my ui.

2. To completely refresh the provider I can call `ref.invalidate` on the provider but that does not call `loading()` again.

Example:

```dart
int counter = 0;
final counterProvider = FutureProvider.autoDispose((ref) async {
  await Future.delayed(const Duration(seconds: 1));
  return ++counter;
});

class MyHomePage extends ConsumerStatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  ConsumerState<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends ConsumerState<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final counter = ref.watch(counterProvider);
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            counter.when(
                data: (data) => Text(
                      '$data',
                      style: Theme.of(context).textTheme.headline4,
                    ),
                error: (error, stackTrace) => const Text('error'),
                loading: () => const CircularProgressIndicator()),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => ref.invalidate(counterProvider),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

**Describe the solution you'd like**
1. I think that `refreshing` should be introduced in `AsyncValue`:

```dart
counter.when(
  data: (data) => Text(
      '$data',
      style: Theme.of(context).textTheme.headline4,
    ),
  error: (error, stackTrace) => const Text('error'), 
  loading: () => const CircularProgressIndicator(),
  refreshing: () => const CircularProgressIndicator());
```

2. I also feel like invalidating the provider should trigger `loading` of `AsyncValue`.

**Comment by rrousselGit** [comment]
The behavior you've described is the one available on the master branch. It has changed since the latest release. See the changelog :) 

On the other hand, I'm skeptical about a  `when(isRefreshing)`. Common use-cases want to, during refresh, show the previous data/error. 

If you want to do what you've described, you could do:

```dart
if (counter.isRefreshing) {
  return Loading();
}

return counter.when(
  data: (data) => Text(
      '$data',
      style: Theme.of(context).textTheme.headline4,
    ),
  error: (error, stackTrace) => const Text('error'), 
  loading: () => const CircularProgressIndicator(),
  refreshing: () => const CircularProgressIndicator());
```

**Comment by rrousselGit** [comment]
An optional parameter could be considered, although I'm still skeptical. Feel free to make a separate issue

**Comment by andreagorrieri** [comment]
Thanks for the insights. Just to leave my feedback here: I totally agree with @krjw-eyev about the "refreshing:" parameter.

**Comment by tonsz** [comment]
Hello, I came across this because I had a problem in my code where the page was having delay in displaying the updated data from a `FutureProvider` and I was invoking `ref.invalidate `on that since it depended in a `StateProvider` that feeds an ID that is needed to fetch the data in the future. 

It was working as intended but I encountered the delay. At the moment, there is no "refreshing:" parameter but rather the `skipLoadingOnRefresh` parameter which I set to false and my problem was solved. 

Commenting now if anyone else comes finding answers. Thank you as well.
