### ISSUE TITLE
Syntactic sugar for reading a provider

### ISSUE THREAD

**Issue by scopendo** [rrousselGit/river_pod#174]
**Is your feature request related to a problem? Please describe.**

In Riverpod, to read a provider's value in an event handler, such as a button's onPressed callback, we use the following syntax:

```dart
final myProvider = StateProvider<int>((ref) => 0);
...
void onPressed(BuildContext context) {
  // Increment my provider's value
  context.read(myProvider).state++;
}
```

To me, this code doesn't feel like it fits in with an idiomatic Flutter "of(context)" pattern.

**Describe the solution you'd like**

To allow code to be more consistent with standard inherited widget Flutter approaches, like Theme.of(context), it might be worth adding a helper method such as:

```dart
extension MyStateProvider<T> on StateProvider<T> {
  StateController<T> of(BuildContext context) {
    return context.read<StateController<T>>(this);
  }
}
```

With this available, the event handler callback from above could be changed to:

```dart
void onPressed(BuildContext context) {
  // Increment my provider's value
  myProvider.of(context).state++;
}
```

By applying a convention that is closer to Flutter's, I wonder if it would make it easier for people to learn Riverpod.

**Comment by rrousselGit** [comment]
That's how it originally worked.

I moved away from that syntax because the target object depends on the situation. It's not just `BuildContext`. We have:

```dart
ProviderReference ref;
ref.read(myProvider);

ProviderContainer container;
container.read(myProvider);

BuildContext context;
context.read(myProvider);
```


All of these works the same (modulo that you use one or another depending on whether you are in the widget tree or in a provider).

Considering Dart doesn't have union type, that would require:

```dart
myProvider.ofContext(context);
myProvider.ofRef(ref);
myProvider.ofContainer(container);
```

which sounds more confusing _in my opinion_.

That would be especially confusing because the `.ofContext` not be available if you imported `package:riverpod/riverpod.art` because that is the dart-only implementation.
When using this syntax, numerous people got confused as to why the read method wasn't available.

**Comment by rrousselGit** [comment]
In the end, if you want such syntax, you can use the following extension:

```dart
extension OfProvider<T> on ProviderListenable<T> {
  T of(BuildContext context) => context.read(this);
}
```

That will work with all providers.

**Comment by scopendo** [comment]
Thanks for that explanation @rrousselGit – I agree given the non-flutter usages that it makes sense to add a custom extension outside of the Riverpod packages.
