### ISSUE TITLE
Rename Provider to Pod

### ISSUE THREAD

**Issue by passsy** [rrousselGit/river_pod#197]
## Description

I'd prefer if riverpods providers would be called "pods".

```diff
-final counterProvider = StateProvider((ref) => 0);
+final counterPod = StatePod((ref) => 0);
```

## Reasoning

- Prevents name collisions with [`provider`](https://github.com/rrousselGit/provider)
- Makes code shorter
- Acronyms make libraries and [concepts popular](https://www.youtube.com/watch?v=PLHln7wHgPE&feature=youtu.be&t=1316). A "pod" is good not an acronym but short
- `Provider` is already a reserved name. I want people saying: "And then you create a new pod..."
- IMHO `Provider` is a bit too generic

## Migration

For the migration, we could:
- temporarily have both names coexist (having both a `Provider` and `Pod` in the package), with *Providers being deprecated
- provide a command line tool to automatically to the migration (akin to `dart fix`, likely implemented using [codemod](https://pub.dev/packages/codemod))

---

Make sure to vote with either :+1: or :-1: to express your opinion, as this is how the decision will be made

**Comment by Marco87Developer** [comment]
I like ‘pod’, and I have nothing against it. Could an alternative be River?

**Comment by joanofdart** [comment]
This is absolutely genius, +1 to this suggestion.

**Comment by rrousselGit** [comment]
The goal of the current naming is to provide an easy path for people to migrate from provider to riverpod.

The package name itself is a representation of how similar both libraries are, as riverpod is an anagram of provider.

By using "pod", that would draw a line between both packages.
Is that really desired?

**Comment by iamarnas** [comment]
I agree with Remi. `Provider` is classic word in the Flutter and all know what it mean it's like `Future`, `Stream`, `Function`, `String`... It same like I would say "I'd prefer `Future` would be called `Later`". I believe who want shorter name can fix it with short extension.

**Comment by rrousselGit** [comment]
About "avoiding name clash with provider"

Would using import alias cover the need?

```dart
import 'package:provider/provider.dart' as provider;
import 'package:flutter_riverpod/flutter_riverpod.dart' as riverpod;

final example = riverpod.Provider((ref) {

});

...
provider.MultiProvider(
  providers: [
    provider.Provider(create: (context) => ...),
  ],
)
```

**Comment by rrousselGit** [comment]
As for `context.read` clashing between both packages, #335 should implicitly cover this, as riverpod would instead do `ref.read` inside widgets (no longer using BuildContext)

**Comment by hisaichi5518** [comment]
I did the migration from provider to riverpod in my work.
During the migration period, when I talked about Riverpod and package:provider with other engineers, I had to explain whether the "Provider" I was talking about was the provider's or Riverpod's, which was annoying.

We can also use an alias at import time, but the IDE doesn't insert an alias automatically. So I had to write the alias myself, and it was very tedious to go back and forth between the logic and the import statement.

So, I agree with this idea.

**Comment by rrousselGit** [comment]
If we're going to do a rename, I believe we could:

- keep the current names, but deprecated
- provide a quick fix to automatically migrate from `*Provider` to `*Pod`

So the migration should be smooth.

But I'd really need confirmation that this is what people want.

**Comment by awhitford** [comment]
I know naming things is probably the hardest part of programming.
* [Provider](https://www.dictionary.com/browse/provider)
  * > a person or thing that provides 
* [Pod](https://www.dictionary.com/browse/pod)
  * > a streamlined enclosure, housing, or detachable container of some kind

Of these two choices, **I prefer Provider based on what it means.**

I'm concerned that choosing _Pod_ is really just a derivation of the anagram of _Provider_ rather than a choice based on choosing an appropriate noun.  Imagine that Remi transformed _Provider_ to _RoverDip_, would we entertain calling them [Rovers](https://www.dictionary.com/browse/rover)?

**Comment by rrousselGit** [comment]
"pod" fits IMO

Providers/Pods are self-contained state units, especially now that with Riverpod, providers are no-longer widgets.
It is likely that as the language evolves, the barrier between the provider and XXNotifiers will fade.

It's worth noting that in JS, they call it "atom".

**Comment by TimWhiting** [comment]
I think of Riverpod as a reactive caching / memoization framework with dependency injection.

As such, I like the name Cache. 
`FutureCache` `StreamCache` `Cache` `StateCache` `StateNotifierCache` `ChangeNotifierCache`.
And the return of Future/Stream could be called `AsyncCache`. It seems to fit what Riverpod does for you. It's a little more explicit than Pod which seems like just a catchy name.

But I also like Pod, as it fits the naming of Riverpod better. Either is better than Provider in my opinion, because Riverpod's uniqueness is not about the dependency injection or providing to the widget tree, but rather about memoizing and reacting to state changes.

**Comment by rrousselGit** [comment]
I don't like "cache" as a name, but I agree with @TimWhiting 

I definitely see Riverpod as a reactive caching mechanism

**Comment by searchy2** [comment]
Renaming would help support partial migrations; using Provider and Riverpod at the same time.
The Pod name isn't explanatory though. I don't like the name as it sounds icky and reminds me of this.
![image](https://user-images.githubusercontent.com/19896174/111915881-5dbddd80-8a46-11eb-8a20-9e313a63a1af.png)

**Comment by bernaferrari** [comment]
I like the Pod, but it would conflict with cocoapods and the iOS world, so searching for anything on Google would get a lot harder! I voted for no.

**Comment by Abacaxi-Nelson** [comment]
Pod confuse me.. i have pods for kubernetes :(

**Comment by rrousselGit** [comment]
"It'll conflict with cocoapod"

 But "provider" conflicts with many things too.
For example for authentication, you're rely on "third-party authentication providers"

**Comment by kranfix** [comment]
@Abacaxi-Nelson I also thought in Kubernetes, but it doesn't mind because Flutter and Kubernetes has nothing in common.  
  
Although you were writing a Flutter App for monitoring your `Kubernetes`' pods with `Riverpod`, there are ways to avoid name conflicts.

**Comment by davidmartos96** [comment]
I like Pod to avoid name clashing with Provider, but if the name is going to be drastically different, using Atom is another option.

**Comment by TimWhiting** [comment]
As far as conflicting names causing search issues, maybe a new name to fit the reactive nature of it: 
Reactor
or
Reactant
or
Coact
or
Impact

but I still think Pod fits best with the name River*pod*, unless you do something *River* related like:
Ripple
or
Drop

Just brainstorming here. I can see why Atom fits.

**Comment by rrousselGit** [comment]
There are quite a lot of people against this change

Even if the majority is in favor, I don't think it is reasonable for this change to pass. We're not electing a president after-all. I would expect a small minority of people to be against a change for it to pass.   
In comparison, the feedback on #341 and #335  is overwhelmingly positive.

So I'm opposed to the renaming

**Comment by TimWhiting** [comment]
@rrousselGit 
From what I've seen it seems like non-function type aliases will be available starting [Dart 2.13](https://dart-review.googlesource.com/c/sdk/+/192948). At that time it would be nice to have Pod typedefs in a library like `package:riverpod/pods.dart` for the many people who were in favor of this, because even though there are a lot of people against the change there were quite a lot in favor of it. Obviously this would make documentation difficult, so I would just mention it in the beginning of the documentation that the typedefs are available and just have the official classes be what is used in the docs.

**Comment by rrousselGit** [comment]
I don't think Riverpod should include such typedefs.
If people want to use a different name, they can define typedefs on their own. 

Having typedefs in the official library would be confusing. Consistency is key

**Comment by iamarnas** [comment]
Good news for all `Pod` type lovers! Now you can rename `Provider` type how you want by [TypeAlias](https://pub.dev/documentation/analyzer/latest/dart_ast_ast/TypeAlias-class.html ) in the Dart 2.13
