### ISSUE TITLE
`select` docstring is either wrong or out of date.

### ISSUE THREAD

**Issue by ghost** [rrousselGit/river_pod#232]
The example given in the docstring for the `select` function of a provider doesn't work.

```dart
class Person extends ChangeNotifier {
  int _age = 0;
  int get age => _age;
  set age(int age) {
    _age = age;
    notifyListeners();
  }

  String _name = '';
  String get name => _name;
  set name(String name) {
    _name = name;
    notifyListeners();
  }
}

final personProvider = ChangeNotifierProvider((_) => Person());

class Example extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final age = watch(personProvider.select((p) => p.age)); // problem
    ...
  }
}
```

The linter gives:
```
The argument type 'ProviderListenable<int>' can't be assigned to the parameter type 'ProviderBase<Object, dynamic>'.
```

This works with `useProvider` though.
It's mentioned in the docs that select syntax is not supported yet by ConsumerWidget (hence the issue). It would be great if it was...

**Comment by oliverfunk** [comment]
I posted that from the wrong account, my bad heh..

**Comment by Ayman-Kortobaa** [comment]
First of all, this package is a great step up from `Provider` and I am loving it!
But this issue is the only thing stopping me from using it in my apps, I don't think that I have to be forced to use hooks just to have the same functionality that the `Provider` package offers.
It would be great if `ConsumerWidget` can use the `myProvider.select` functionality like the docstring states.
