### ISSUE TITLE
BuildContext extension "read" doesn't accept a ScopedProvider

### ISSUE THREAD

**Issue by rich-j** [rrousselGit/river_pod#274]
The `BuildContext` extension method for `read` accepts a `RootProvider` which excludes `ScopedProvider`. The underlying extension implementation uses `ProviderScope.containerOf(...).read` which accepts a `ProviderBase` that allows `ScopedProvider`. Could the extension `read` accept a `ProviderBase` which would then support the concise `context.read(aScopedProvider)`? Our current workaround is to use the longer `containerOf` implementation.

**Comment by TimWhiting** [comment]
I also would like to see this if it is feasible. I add my own extensions on BuildContext to read various state and they could be getters/setters instead of methods if I could read a scoped provider from BuildContext.

**Comment by matuella** [comment]
Agreed, if it's not possible to be `context.read`, it also could be improved with some sort of documentation, IMO. I think this issue is relevant, because there is no documentation at all about `ScopedProvider` (nor this stuff about context`.read`) and, when I first search for it in the issues, I found the issue #257, which is not only related to this exact problem, but it has lead me to think that `ScopedProvider` couldn't be `read`, which I eventually found out that I could achieve it through a `ScopedProvider.containerOf`.

**Comment by matuella** [comment]
Also, just for reference, I've faced the same issue when referencing a `ScopedProvider` inside another `Provider`, which we don't have a `BuildContext` instance. In this case, you can access the container through the `ProviderReference` by calling `ref.container.read`, like in the example below.

```dart
final scopedProvider = ScopedProvider<String>((_) => 'scoped provider');
final parentProvider = Provider<String>((ref) => 'parent of ' + ref.container.read(scopedProvider));
```

**Comment by rrousselGit** [comment]
> In this case, you can access the container through the `ProviderReference` by calling `ref.container.read`, like in the example below.
> 
> ```dart
> final scopedProvider = ScopedProvider<String>((_) => 'scoped provider');
> final parentProvider = Provider<String>((ref)
> ```

That's a bug. 

Don't do that

**Comment by rrousselGit** [comment]
I'll try and fix this bug during the week. A bit busy but that should be fine

The painful part is testing.

**Comment by yupi** [comment]
Sorry for being late but the very same problem happens when trying to `context.read()` a provider created with basic Provider class. For example:

`final accountServiceProvider = Provider<AccountService?>((ref) {
...
});`

then trying to get the provider it like
`final service = context.read(accountServiceProvider);`

gives an error:
The argument type 'Provider<AccountService?>' can't be assigned to the parameter type 'ProviderBase<Object, dynamic>'.

though it works as `final service = ProviderScope.containerOf(context, listen: false).read(accountServiceProvider);` which is essentially a `context.read()`.

**Comment by rich-j** [comment]
Thanks @rrousselGit - as @yupi points out above we could use the `Object` type of the `read` extension to be nullable, which is the same type as the underlying `containerOf(...).read`:

```dart
T read<T>(ProviderBase<Object?, T> provider) {
//                         ^nullable
```

I just changed all of our code to the `read` extension method :-) and found 1 case of a nullable `ScopedProvider` which doesn't type check. I believe that it's reasonable for a `ScopedProvider` to be null - for us it's a value that's not available during startup/sign-in but once in the main code scope it's provided.
