### ISSUE TITLE
How to clear cache in Provider.family?

### ISSUE THREAD

**Issue by khoadng** [rrousselGit/river_pod#318]
**Is your feature request related to a problem? Please describe.**
I have a provider like this to get data from the server.

```dart
final postProvider =
    FutureProvider.autoDispose.family<List<Post>, int>((ref, page) async {
  final repo = ref.watch(repoProvider);
  final posts = await repo.getData(page); 

  return posts;
});
```

It is working perfectly but when I tried to call this provider again with the same parameter to refresh the data, it always returns the cache.

**Describe the solution you'd like**
Is there any way to clear the cache? Or is there a better approach to my problem?

**Comment by rrousselGit** [comment]
You can call `context.refresh(postProvider(id))`

**Comment by Yogi-6** [comment]
How can we clear a family provider's cache for all of the different inputs at once? The StackOverflow [example](https://github.com/rrousselGit/riverpod/blob/master/examples/stackoverflow/lib/home.dart) can be used as a starting point:
```
RefreshIndicator(
    onRefresh: () {
        ref.refresh(paginatedQuestionsProvider(0));
        return ref.read(paginatedQuestionsProvider(0).future);
    }
)
```
This appears to clear the cache only for only input 0; if I scroll down to page 1 or 2, for instance, I will see the cached result.

How do refresh only the first page and dispose of all the other inputs so that on scroll down the API call is made and all the new results are returned? One naive approach that comes to my mind is to keep track of all the inputs and dispose of them iteratively when pull-to-refresh is called. I am looking for a better way to accomplish this. Thanks!
