### ISSUE TITLE
Why to avoid using read and prefer watch, which is generally safer to use?

### ISSUE THREAD

**Issue by binodsarkar** [rrousselGit/river_pod#321]
**Confution between ref.read and ref.watch when combining providers**
I have gone through the riverpod documentation here https://riverpod.dev/docs/concepts/combining_providers. I am getting confused with the statement "If possible, avoid using read and prefer watch, which is generally safer to use" when reading provider inside another provider. 

1. It is not clear that why context.watch is more safer? 
2. What is the problem I am going to face if I use contxt.read inside provider.
3. contxt.read should not be use inside body of a provider - is it applicable for Provider() only or for other providers like FutureProvider also? whats the wrong with it?

**Comment by gautamr** [comment]
Having the same confusion :)

**Comment by smiLLe** [comment]
Ok, small example:
```dart
final stringProvider = StateProvider<String>((_) => 'Foo');
final intProviderWatch = Provider<int>((ref) => ref.watch(stingProvider).state.length);
final intProviderRead = Provider<int>((ref) => ref.read(stingProvider).state.length);

Widget build(context) {
  /// we use hooks, but this is the same for ConsumerWidget
  print('watch ' + useProvider(intProviderWatch));
  print('read ' + useProvider(intProviderRead));

  return Button(onPressed: () => context.read(stringProvider).state = 'Hello');
}
```
Lets assume your Widget build.
This will print  as expected
// watch 3
// read 3

Now we press the Button which will set stringProvider to 'Hello'.
`intProviderWatch` will be automatically updated because it uses `.watch`. This means it will now hold an int value of 5.
`intProviderRead` will not update because it used `.read`. This means it will still hold an int value of 3.

Also lets assume our Widget build looked like this:
```dart
Widget build(context) {
  /// This will not print 'read 5' after we press the button, because the intProviderRead will never be updated
  /// This means that this widget will not rebuild
  print('read ' + useProvider(intProviderRead));

  return Button(onPressed: () => context.read(stringProvider).state = 'Hello');
}
```

```dart
Widget build(context) {
  /// This will always print the updated int, whenever you change stringProvider.state
  /// This means, that this widget will rebuild.
  print('watch ' + useProvider(intProviderWatch));

  return Button(onPressed: () => context.read(stringProvider).state = 'Hello');
}
```

**Comment by TimWhiting** [comment]
To be clear there are use cases where `.read` is appropriate (I know I have a few, but they are more complex than I care to explain). But you should default to using `.watch` unless you see a use case that requires `.read`. Watch will always mean that all providers are up to date with the providers they depend on, whereas read means they will just grab the current state of the other provider.

**Comment by binods-gintaa** [comment]
Thank you all for your support. So, the conclusion is we should use watch whenever it is possible. Any comment on my questions  2 and 3?

Thanks in advance

**Comment by iamarnas** [comment]
@binods-gintaa In short `.read` only read on first run, `.watch` read on any changes and will rebuild your UI.

**Comment by rrousselGit** [comment]
Using `read` inside the body of a provider is a bad practice because it is weak to refactoring and a potential source of mistakes.

It is possible to use `watch` and achieve the exact same behaviour (not rebuilding). As such, using read instead of watch doesn't bring any extra functionality. Therefore since read is more dangerous than watch, use watch.


How is read "dangerous"?
- it will not make 'maintain the state' of the obtained provider if it is using `autoDispose`.
  This means that when doing:

  ```dart
  final value  = ref.read(provider);
  await doSomething();
  value.doSomething();
  ```
  Then by the time `value` is used, it may have been disposed of.


- As applications grows, needs changes. Maybe the provider that "never changed" before will in the future. For example maybe you've used `context.refresh` or `autoDispose`, or that provider now watches another provider.
  In that scenario, places using `read` would likely have a bug: they wouldn't handle the update. But that's going to be very hard to catch.  
  With watch? That'd work automatically.

**Comment by binodsarkar** [comment]
Thank you all

**Comment by rrousselGit** [comment]
Keeping this open as a reminder to improve the documentation on that area

**Comment by matpag** [comment]
> Keeping this open as a reminder to improve the documentation on that area

I had the same confusion of the OP because checking the example here:
https://github.com/rrousselGit/river_pod/blob/55192e8bd1629a416b1242d8574ff2878d6103d4/examples/marvel/lib/src/screens/home.dart#L27-L49
they are using `ref.read(repositoryProvider)` at line 37, which is inside a Provider

**Comment by rrousselGit** [comment]
Eh I probably was lazy 🙈 
I'll fix that too.

**Comment by jamesdixon** [comment]
Holy heck, just found this thread and using `read` was exactly the problem. Mistakenly thought that using `read` was an optimization when I didn't need a provider to trigger upon change.

**Comment by anticafe** [comment]
Well, thanks all for your information. So we should use `.watch` as default?

**Comment by rrousselGit** [comment]
Yes, use watch as default

In watch I've been thinking for a while that `read` could be removed.

In the end, the only reason it exists is for `StateNotifier`. Even widgets don't need it with the recent `watch(provider.notifier)` updates.

**Comment by sgehrman** [comment]
Why isn't there context.watch() ?

**Comment by rrousselGit** [comment]
I'll close this since the documentation is now clearer about the problems with `read`
