### ISSUE TITLE
Document how to do organize a Providers-subgraph with a generic argument that is instantiated multiple times  

### ISSUE THREAD

**Issue by derolf** [rrousselGit/river_pod#348]
EDIT: better example here https://github.com/rrousselGit/river_pod/issues/348#issuecomment-784459986

What’s the proper approach to nesting?

Is this okay or is it overuse of Provider and I should rather go with Listenables inside?

```
class Repo<T> {
  void add(T obj) ...
  
  late final Provider<List<T>> all = ...
  late final Provider<List<T>> even = ...

}

final myIntRepo = Provider((ref) => Repo<int>());

final myDoubleRepo ...
```

Provider looks like a Swiss-army-knife replacement to ValueListenable...

**Comment by rrousselGit** [comment]
I would advise against having non-static providers, unless you know what you're doing.
Or at the very least, mark them with `autoDispose`


But I don't quite understand why you would want that.

**Comment by derolf** [comment]
Actually, the use-case got a bit lost when I wrote the abstraction above.

I have a persistent repository for different entity types. The repository API is uniform and parametrized with a type.

So, I instantiate a bunch of global repositories that contain the providers.

The mistake in the example above is that I don’t need to provide the Repo-instance with Provider because all the fields are the actual Providers.

**Comment by rrousselGit** [comment]
It sounds to me like you want to create a custom provider

There's no official support for this. But as long as there's no state in your Repo class, your method should be fine.

**Comment by TimWhiting** [comment]
@rrousselGit 
Should this be documented, in an advanced use cases section? Or should there be better official support for creating a custom provider? I've done similar nesting in some personal use cases. But like you said, you have to be careful about it.

**Comment by rrousselGit** [comment]
What's the use-case?

I don't really see why this would be needed, so I doubt it should be documented. But maybe I'm missing something.

**Comment by derolf** [comment]
Better example:

```Dart
import 'package:built_collection/built_collection.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

class RepositoryProvider<K, V> {
  final objects = StateProvider((ref) => BuiltMap<K, V>());

  late final AutoDisposeProviderFamily<Iterable<MapEntry<K, V>>, bool Function(K)> where =
      Provider.autoDispose.family((ref, bool Function(K) test) => ref.watch(objects).state.entries.where((e) => test(e.key)));
}

final people = RepositoryProvider<String, Person>();
final vehicles = RepositoryProvider<String, Vehicle>();
```

**Comment by TimWhiting** [comment]
For example I have a game server. 

It hosts multiple games. Each game has several bits of loosly coupled state.
- PlayerList (For the lobby)
- GameConfig
- GameErrors
- GameState
- etc

So I have a provider for a game, that contains providers for each of these bits of state.
Obviously I could have families for all of them, and connect the bits of state together with a GameCode.

But I found that it was quite unwieldy to have so many families. Especially since the lifecycle of all of these providers are dependent on the parent lifecycle. 

So my `GamesProvider` is a family, but then it nests all of these interconnected bits of state together. It also hands down to each of these providers a `GameReader` that wraps a `Reader`, but knows about the game code / specific `GameProvider` so that the providers can access each other without having to explicitly know about the game code, and also keeps them isolated from other games to keep the code cleaner. The advantage of using nested providers over something like nested `StateNotifier`s inside the top level `GameProvider` is that I can have the providers watch and read from each other by just having a `ref`, and not have to worry about the `addListener` / `removeListener` subscribe / dispose lifecycle except in the provider creation function.

I've found that Riverpod is very flexible and powerful if you know what you are doing, but I might be making things unnecessarily complex.

**Comment by rrousselGit** [comment]
>But I found that it was quite unwieldy to have so many families. Especially since the lifecycle of all of these providers are dependent on the parent lifecycle.

Could you expand on that?

**Comment by TimWhiting** [comment]
Imagine 5-10 families that are parameterized on the same piece of data (game code) in my case. As soon as the game is created all of these providers should become available, and when the game ends, all of the providers should be cleaned up.

Instead of passing around gameCode everywhere in my code that I want to read these I just want to be able to read them with some reference to a `GameReader` which knows about the game code. I guess I could still declare them as families, and have the `GameReader` read them based off of the game code, but it became an organization issue, where I wanted to group these related providers, and enforce access to them through this `GameReader`. 

Also what happens if you want a nested family (yes you could just have an object with multiple fields instead, but you lose the grouping of family providers by common accessor).

**Comment by derolf** [comment]
I was just browsing the docs, but isn’t `StreamProvider` a kind of nested provider? Basically both `steam` and `last` are nested providers within the `StreamProvider`.

I think the confusing piece is that `Provider`s are actually factories until someone watches or reads them.

What I understand is that one should not nest a Provider inside an actual provided instance.

So if you need to write `context.watch(context.watch(foo).bar)`, something is broken...

**Comment by rrousselGit** [comment]
It isn't a _nested provider_. It's just a provider

I'd consider nested providers something like:

```dart
class Repository {
  final provider = Provider(...);
}

final repository = Provider((ref) => Repository());
```

This is different from:

```dart
class Repository {
  final provider = Provider(...);
  
  final provider2 = Provider(...);
}

final repository = Repository();
```

**Comment by rrousselGit** [comment]
What you've done is fine. It's not very different from `.family`

`.family` is in fact nothing but a `Map<Param, Provider>` really.
What you made is a family with pre-determined keys.

That's a useful pattern. I don't think there's anything wrong with it (besides being far more advanced)

**Comment by derolf** [comment]
Anti-pattern (nesting a Provider instance an instance of another Provider):

```dart
> class Repository {
>   final provider = Provider(...);
> }
> 
> final repository = Provider((ref) => Repository());
> ```

Correct approach:

> ```dart
> class Repository {
>   final provider = Provider(...);
>   
>   final provider2 = Provider(...);
> }
> 
> final repository = Repository();
> ```

**Comment by rrousselGit** [comment]
To be specific, the correct approach is:

```dart
@immutable
class Repository {
   final provider = Provider(...);   
   final provider2 = Provider(...);
} 

final repository = Repository();
```

**Comment by davidmartos96** [comment]
@rrousselGit So that repository would be globally initialized just for the purpuse of "organizing" other providers right? One would access the providers via `watch(repository.provider)` ?

**Comment by derolf** [comment]
> @rrousselGit So that repository would be globally initialized just for the purpuse of "organizing" other providers right? One would access the providers via `watch(repository.provider)` ?

You need to scroll up a bit. The underlying use-case is having a generic `Repository<T>` that contains a few providers and then use multiple instances globally.

**Comment by rrousselGit** [comment]
If it's just for organisation, you can do:

```dart
abstract class TodoList {
  static final provider = Provider<List<Todo>>(...);

  static final length = Provider((ref) => ref.watch(provider).length);
}


....

final todos = watch(TodoList.provider);
```

**Comment by derolf** [comment]
Well the emphasis of this “advanced documentation ask” is “how do you do provider families where the argument is a type?” :-)...

**Comment by derolf** [comment]
> If it's just for organisation, you can do:
> 
> ```dart
> abstract class TodoList {
>   static final provider = Provider<List<Todo>>(...);
> 
>   static final length = Provider((ref) => ref.watch(provider).length);
> }
> 
> 
> ....
> 
> final todos = watch(TodoList.provider);
> ```

```
@immutable
class TodoList<T> {
  final provider = Provider<List<T>>(...);

  late final length = Provider((ref) => ref.watch(provider).length);
}


....

final officeTodos = TodoList<OfficeTodo>();

final kitchenTodos = TodoList<KitchenTodo>();

....

final todos = watch(officeTodos.provider);

```

**Comment by rrousselGit** [comment]
That's different ,as it isn't for organisation for something else.
