### ISSUE TITLE
How to dispose a provider manually?

### ISSUE THREAD

**Issue by davebound** [rrousselGit/river_pod#367]
I hope this isn't a stupid question.

I know I can use autoDispose() to dispose a provider when there are no more watch()ers, but how to dispose manually?

Here's my provider

```
final gProvMatches = Provider /*.autoDispose*/ <MatchesProvider>(
  (ref) {
    if (glog) gl.i('CREATING PROVIDER gProvMatches');

    ref.onDispose(() {
      if (glog) gl.c('DISPOSING PROVIDER gProvMatches');
    });

    final ret = MatchesProvider(repo: ref.read(gProvRepositoryService));
    if (glog) gl.o();
    return ret;
  },
);
```

(It constructs a MatchesProvider)

Here's where I use it

```
suggestionsCallback: (pattern) async {
        return await context.read(gProvMatches).getMatchesTypeahead(widget.fieldName, pattern, widg.showAllIfEmptyPattern);
      },
```

(That causes the MatchesProvider to be constructed)

So.... how do I manually get ref.onDispose() to fire?

**Comment by smiLLe** [comment]
You can not dispose an non `AutoDispose Provider`. Why is it not possible for you to use `AutoDispose`?

**Comment by davebound** [comment]
suggestionCallback gets called fairly often. The context.read() call constructs MatchesProvider. But MatchesProvider is quite expensive to construct. If I use autoDispose() MatchesProvider gets disposed as soon as suggestionCallback exits. I'd like it to stick around for longer.

**Comment by rrousselGit** [comment]
Maybe do:

```dart
final matches = watch(gProvMatches);

...
suggestionsCallback: (pattern) async {
        return matches.getMatchesTypeahead(widget.fieldName, pattern, widg.showAllIfEmptyPattern);
},
```

**Comment by tbm98** [comment]
I have a case that needs manual dispose. 
That is, when I have a provider that provides a controller class, this class contains the entire logic of a page, it doesn't necessarily hold state, I want to separate the business logic from the UI logic. I want it to hold a `ProviderReference` so that it can access other `Providers` as well and retrieve it by `context.read`. currently if I use `Provider.autoDispose` it will re-initialize every time I use it, if I use `Provider` it will never dispose and there is no way to dispose it. 
There is another alternative, which is to manually initialize the Controller class and assign `ProviderReference` later, but I think that's not a good way: D

**Comment by tbm98** [comment]
use `watch` to help me dispose of my controller when the view is disposed, but still can't dispose of by manually.
And what's more, I can't use `context.watch` and have to use `ConsumerWidget` or `Consumer` instead. It is quite inconvenient in this case.

**Comment by iamarnas** [comment]
@tbm98 With StateNotifier you can do this trick.

**Comment by tbm98** [comment]
> @tbm98 With `StateNotifier` you can do this trick.
> 
> If I'm not wrong.

@iamarnas yes I know StateNotifierProvider can provide a `StateNotifier` with a `State` as a pair, but in some case, I don't want to store the whole state of a page into a single state object or I just want a class to hold my business code instead of putting it together UI code, instead, I want to separate them into many different providers, in normally we store state in a provider and put all of handle business code and UI logic code into State (or StatelessWidget).

I want to put handle business code into another class, for example
```dart
class _PDFViewingPageState extends State<PDFViewingPage> {

  bool get _isPdfFileValid =>
      widget.pdfFile != null && widget.pdfFile.path.isNotEmpty;

  @override
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, watch, child) {
        return Scaffold(
          appBar: AppBar(),
          body: Container(
            child: _buildBody(),
          ),
        );
      },
    );
  }

  Widget _buildBody() {
    if (_isPdfFileValid) {
      return SfPdfViewer.file(widget.pdfFile);
    } else {
      return PdfErrorWidget();
    }
  }
}
```
I want to put the validation into another class like this

```dart
class Controller {
  Controller(this.ref);

  // maybe I will use ref to access to another provider
  ProviderReference ref;

  bool isPdfFileValid(File? file) {
    return file != null && file.path.isNotEmpty;
  }
}

class _PDFViewingPageState extends State<PDFViewingPage> {


  // init it somewhere
  Controller? controller;
  
  

  @override
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, watch, child) {
        return Scaffold(
          appBar: AppBar(),
          body: Container(
            child: _buildBody(),
          ),
        );
      },
    );
  }

  Widget _buildBody() {
    // controller have been init somewhere
    
    if (controller.isPdfFileValid(widget.pdfFile)) {
      return SfPdfViewer.file(widget.pdfFile);
    } else {
      return PdfErrorWidget();
    }
  }
}
```

**Comment by rrousselGit** [comment]
Then do not use `context.read`, and use `watch`

In general I would advise against using `context.read`, especially when using `autoDispose`.
To the point where I'm thinking about either making autoDispose+read a compilation error, or remove `read` entirely, or revemp `read` to make it keep the providers alive until the widget that did read a provider gets disposed.

**Comment by tbm98** [comment]
Yep. So I think use Provider vs watch is the best choice for my case 🤔

Vào 5:45, Th 6, 26 thg 3, 2021 Remi Rousselet ***@***.***> đã
viết:

**Comment by rrousselGit** [comment]
Closing since this seem to be resolved
