### ISSUE TITLE
Bug where a provider that isn't listened is still rebuilding

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#746]
From an offline discussion: 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

int globalCount = 0;

final root = FutureProvider<int>((ref) async {
  print('Building `root` provider...');
  await Future.delayed(const Duration(seconds: 1));
  return globalCount++;
});

final formattedCount = FutureProvider<String>((ref) async {
  print('Building `formattedCount` provider...');
  final count = await ref.watch(root.future);
  if (count > 1) {
    print('EXCEPTION');
    throw Exception();
  }
  return "count: $count";
});

final result = FutureProvider<String>((ref) async {
  print('Building `result` provider...');
  final count = await ref.watch(root.future);
  if (count > 1) return 'too high';
  final result = await ref.watch(formattedCount.future);
  return result;
});

void main() {
  runApp(
    const ProviderScope(
      child: ExampleApp(),
    ),
  );
}

class ExampleApp extends ConsumerWidget {
  const ExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final label = watch(result);
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: label.map(
            data: (data) => Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(data.value),
                ElevatedButton(
                  child: const Text('Increment'),
                  onPressed: () {
                    print('REFRESH -----');
                    context.refresh(root);
                  },
                )
              ],
            ),
            loading: (loading) => const Text('Loading'),
            error: (error) => Text('Error: ${error.error}'),
          ),
        ),
      ),
    );
  }
}
```

prints:

```
Restarted application in 707ms.
flutter: Building `result` provider...
flutter: Building `root` provider...
flutter: Building `formattedCount` provider...
flutter: REFRESH -----
flutter: Building `root` provider...
flutter: Building `formattedCount` provider...
flutter: Building `result` provider...
flutter: REFRESH -----
flutter: Building `root` provider...
flutter: Building `formattedCount` provider...
flutter: Building `result` provider...
flutter: EXCEPTION
```

**Comment by TimWhiting** [comment]
Some feedback on this - I might be wrong but this bug seems expected to me.

This seems to be an ordering issue:

## FIRST BUILD
Dependency graph from listeners
* `result` -> `root` , `result` -> `formattedCount`, `formattedCount` -> `root`
## SECOND BUILD
* `root` rebuilds causing `result` & `formattedCount` (it's direct dependencies) to be outdated
* (Assuming you rebuild from the top of the graph downwards) `root` rebuilds first
* since `result` depends on `formattedCount`, `formattedCount` should be built first
* `formattedCount` still depends on `root`
* `result` is rebuilt and still depends on both `root` and `formattedCount`
* Dependency graph stays the same
## THIRD BUILD
* `root` rebuilds causing `result` & `formattedCount` to be outdated, root must rebuild. 
* Both other providers are outdated & need rebuilding
* According to the last dependency graph `formattedCount` should rebuild first since it is needed by `result`, 
* but lets say there are two options:
  1. (built from top of graph down) if `formattedCount` rebuilds first then it will throw an exception
  2. (built from bottom of graph up) if `result` rebuilds first then `formattedCount` is no longer listened to 
  by anyone and therefore technically does not need rebuilding but is still in the 'queue' for rebuilding 
  since it depended on `root` and `root` was rebuilt. It probably should not be rebuilt until someone new 
  listens to it (it needs to be dirty but not rebuilt until a new listener listens) 
   -- since this provider is not `autoDispose` and shouldn't be disposed --
   either 1 you can eagerly rebuild to avoid this problem of having to rebuild on the next watch of the provider, 
   or 2 you can just mark as dirty, and require that it be rebuilt when the next thing watches the provider.


Either way it seems like the exception is currently expected, unless the order for the rebuilding queue is from the bottom of the graph to the root, lazily recomputing dirty providers on the way up and removing them from the queue if no longer listened. I don't know enough to know if this is the case.

**Comment by rrousselGit** [comment]
Hum you are correct. This indeed looks expected

**Comment by aloisdeniel** [comment]
Hello ! 

> According to the last dependency graph formattedCount should rebuild first since it is needed by result,
>  (built from top of graph down) if formattedCount rebuilds first then it will throw an exception

This can feel unnatural to me. I first thought that provider value evaluation was done during the `watch` call, but providers are actually re-evaluated beforehand, and before method execution.

Thanks for clarification.

**Comment by rrousselGit** [comment]
For reference, this is necessary to properly filter provider rebuilds

In particular, when we do:

```dart
Provider((ref) {
  ref.watch(anotherProvider.select((v) => v.something))
})
```

Then we don't want our provider to rebuild if "something" hasn't changed.

This requires rebuilding "anotherProvider" before rebuilding this provider.
