### ISSUE TITLE
maybeWhen with FutureProvider and conditional await

### ISSUE THREAD

**Issue by c-antin** [rrousselGit/river_pod#783]
**Describe the bug**
If a `FutureProvider` contains a conditional `await`, the `orElse` callback of the `maybeWhen` is invoked even if the condition is `false`.

**To Reproduce**

```dart
final loadProvider = FutureProvider<ObjectThatNeedsLoading>((ref) async {
  final obj = ref.watch(providerOfObjectThatNeedsLoading);
  if (condition) await obj.load();
  return obj;
});

Widget build(BuildContext context, WidgetRef ref) {
  final obj = ref.watch(loadProvider);
  return obj.maybeWhen(
    orElse: () => Container(),//this is called even if the condition is false and the load never happened
    data: (snapshot) {
      return Text('$snapshot');
    },
  );
}
```

**Expected behavior**
`orElse` should not be invoked if `await` never happens.
Current workaround via `FutureBuilder`:

```dart
Widget build(BuildContext context, WidgetRef ref) {
  return FutureBuilder<ObjectThatNeedsLoading>(
    future: ref.watch(loadProvider.future),
    builder: (BuildContext context, AsyncSnapshot<ObjectThatNeedsLoading> snapshot) {
      if (snapshot.hasData) {
        return Text('${snapshot.data}');
      } else {
        return Container();//this gets only invoked if the condition is true and the loading takes place
      }
    },
  );
}
```

**Comment by TimWhiting** [comment]
This is because a FutureProvider uses a Future<T> under the hood -> not a FutureOr<T> so things have to be awaited but there needs to be a state for the provider synchronously so a loading state is what it has to start. I'm looking into how difficult it would be to have FutureProvider use FutureOr<T>

**Comment by TimWhiting** [comment]
See the dart language issue: https://github.com/dart-lang/language/issues/606#issue-502314874. 

You can't use async keyword when you want to have a FutureOr<T> because the await keyword implicitly makes the function return Future even if it doesn't on a particular code path.

This is how you get it to work with how dart works now.
```dart
final loadProvider = FutureProvider<ObjectThatNeedsLoading>((ref) {
  final obj = ref.watch(providerOfObjectThatNeedsLoading);
  if (false) return obj.load().then((_) => obj);
  return obj;
});
```

**Comment by rrousselGit** [comment]
Indeed Tim is correct. So it's not really a bug with Riverpod, but rather a mistake.

Although the change to enable FutureOr hasn't been published yet. So there's nothing you can do right now.

**Comment by rrousselGit** [comment]
With `FutureProvider` now accepting a `FutureOr` as result, you should be able to do what Tim described here https://github.com/rrousselGit/river_pod/issues/783#issuecomment-932815810

So I'll close this
