### ISSUE TITLE
Riverpod Migrate Recommended Changing Import Path

### ISSUE THREAD

**Issue by FXschwartz** [rrousselGit/river_pod#840]
**Describe the bug**
OS - `Windows 11`
Flutter Version - `Flutter 2.5.2`
Dart Version - `Dart 2.14.3`
Riverpod Version - `hooks_riverpod: ^0.14.0+4`
Riverpod CLI Version - `riverpod_cli: ^1.0.0-dev.6`

1. Ran `riverpod migrate` in project root directory
2. Displayed a recommended change to an import path that would break the import

**To Reproduce**
I've only been able to reproduce this on my clients application

**Expected behavior**
I'm not sure why it would recommend changing file import paths but I don't think it should.

![image](https://user-images.githubusercontent.com/16527593/138484548-4ef1b9e9-92bd-4853-b5a0-6e4b47faf22b.png)
![image](https://user-images.githubusercontent.com/16527593/138485422-e2323661-b058-4cdf-aef3-521e198bf6f7.png)

**Comment by TimWhiting** [comment]
@FXschwartz 
Can you check out this branch of my fork?

https://github.com/TimWhiting/river_pod/tree/fix_build_method

Then go into the packages/riverpod_cli folder and activate it using:
`dart pub global activate -s path .`

Then try running `riverpod migrate` in your other project.

Not sure if it actually addresses this specific issue, because I haven't been able to replicate it, but it addresses some other issues I was seeing with migrating those files.

**Comment by FXschwartz** [comment]
@TimWhiting Sorry, still the same issue. Here's confirmation that I'm using your fork.
![image](https://user-images.githubusercontent.com/16527593/139553651-370cc1bc-7e85-4520-84da-a3c18f79d6f6.png)

**Comment by TimWhiting** [comment]
Looks like you are on the master branch of my fork? Can you try switching branches to fix_build_method

**Comment by FXschwartz** [comment]
Oh my bad, but hey! That looks like it fixed it!

It is no longer recommending an import path change and is now correctly recommending an addition to the method parameters!

What do you think the issue was?

![image](https://user-images.githubusercontent.com/16527593/139555059-6db19c02-401e-4d1f-bf76-592947af0946.png)

**Comment by TimWhiting** [comment]
When determining how to migrate functions that used the `useProvider` hook, I needed to keep track of the functions and their dependencies, so that I could thread through a WidgetRef to where it was needed. However, I was only identifying functions by names, and not by file or line. Making it be more explicit about unique functions with the same names fixed the problem.

You likely had multiple functions with the same name. Since I wasn't ensuring uniqueness of functions I was likely using the offset into the file from one function for migrating a different function in a different file. Obviously the file offsets will not line up and you get things inserted in weird places.

**Comment by TimWhiting** [comment]
Let me know if you see further issues. While the migration tool is not guaranteed to be flawless or know how to migrated everything, it should still be decent enough so that you don't have to work through a large migration by hand.
