### ISSUE TITLE
Access previous value of a FutureProvider

### ISSUE THREAD

**Issue by richardjharris** [rrousselGit/river_pod#930]
**Is your feature request related to a problem? Please describe.**
I have a search page that refreshes whenever the input text field is updated. I currently do this by having a `searchResultProvider` (`FutureProvider`) that watches `searchTextProvider` (`StateProvider<String>`) and makes a search request. Then the search result UI watches `searchResultProvider` and updates itself. The problem is, whenever a key is typed the Future changes back to loading, so the interface repeatedly flickers between results and a loading page.

**Describe the solution you'd like**
I would like a way of accessing the previous value so I can just assign `searchResults.when(loading: (previous) => ... use previous value ...)`. Or if you could tell me the recommended solution to this problem, I would appreciate it.

**Describe alternatives you've considered**
My previous code used vanilla Flutter with a FutureBuilder. This code never had any flickering problem, as the snapshot always 'had data'.

I considered using a Stream or wrapping the provider with another one that remembers the previous value, but my Flutter/Riverpod skill is too low to understand how to do this.

**Comment by daniellampl** [comment]
A `FutureProvider` returns nothing more than an `AsyncValue`. When the future, that gets provided, changes (e.g. when your watched `searchTextProvider` changes), the state of the `AsyncValue` gets set to `AsyncValue.loading` by default until the future completes with value or error. This results in always showing your loading page whenever the future of the `FutureProvider` gets updated. 

Accessing the previous state in the `loading` track of an AsyncValue was actually part of `flutter_riverpod` before, but got removed with version 1.0.0. You can read more about this here: https://github.com/rrousselGit/river_pod/discussions/905

An easy fix would be to make a `ConsumerStatefulWidget` where you store the value` in the `ConsumerState`, whenever the `FutureProvider` emits a new value and executes the data track, but without calling `setState`. And in the loading part of the provider, you could return the result page, if the value stored in the widget is not null. Otherwise, you show the loading page. I would consider this only a workaround until a better solution is available. Like so:

```
class TestWidget extends ConsumerStatefulWidget {
  @override
  _TestWidgetState createState() => _TestWidgetState();
}

class _TestWidgetState extends ConsumerState<TestWidget> {
  int? previousValue;

  @override
  Widget build(BuildContext context) {
    return ref.watch(testProvider).when(
          data: (value) {
            previousValue = value;
            return ResultPage(data: value);
          },
          error: (_, __) => const Text('Error ocurred!'),
          loading: () {
            if (previousValue != null) {
              return ResultPage(data: previousValue);
            }
            return LoadingPage();
          },
        );
  }
}

```
Another solution would be to create a `StateNotifierProvider` that provides an `AsyncValue<SearchResult>`. So you can handle the loading state of the `AsyncValue` on your own in the corresponding `StateNotifier`/`StateController`.

**Comment by richardjharris** [comment]
Thanks, I tried your approach and it works great!

**Comment by rrousselGit** [comment]
Do note that I plan on streamlining this sort of thing. Although I'm still in the design phase of this API

**Comment by rrousselGit** [comment]
Closing since #1036 was implemented
