### ISSUE TITLE
How do I pass ref FakeStateNotifierProvider in WidgetTest

### ISSUE THREAD

**Issue by jpoh281** [rrousselGit/river_pod#947]
``` dart
class FakePhoneVerificationController extends StateNotifier<VerificationState>
    implements PhoneVerificationController {
  FakePhoneVerificationController(this._ref) : super(const VerificationState.init([]));
}

testWidgets('phone number validation', (WidgetTester tester) async {
    await tester.pumpWidget(ProviderScope(
      overrides: [
        phoneVerificationControllerProvider.overrideWithProvider(FakePhoneVerificationController(${I Want to Pass Ref}))
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: RVTheme.themeData,
        home: const SignUpFormScreen(),
      ),
    ));
```

How do I pass ref?

**Comment by daniellampl** [comment]
you could access the `ref` by overriding the `StateNotifierProvider` the `PhoneVerificationController` gets created for by creating a new Provider for it. Therefore you can access the ref inside the provider's create callback.

```
phoneVerificationControllerProvider.overrideWithProvider(StateNotifierProvider<PhoneVerificationController, VerificationState>((ref){
    return FakePhoneVerificationController(ref);
 }))

```

I would generally suggest you pass instances (services, repositories, ...) that you might access via the `ref` inside the `PhoneVerificationController` directly, instead of passing the whole `ProviderRef`.

```
final phoneVerificationProvider = StateNotifierProvider<PhoneVerificationController, int>((ref) {
    // instance instead of ref  
    return PhoneVerificationController(ref.watch(someServiceProvider));
});
```

Another possibility would be to mock your `PhoneVerificationController` with the help of `mockito` or `mocktail`and override the value of the `phoneVerificationProvider` with the mocked instance.

**Comment by jpoh281** [comment]
you could access the ref by overriding the StateNotifierProvider the PhoneVerificationController gets created for by creating a new Provider for it. Therefore you can access the ref inside the provider's create callback.

I use this style, thank you!

``` dart
phoneVerificationControllerProvider.overrideWithProvider(StateNotifierProvider<PhoneVerificationController, VerificationState>((ref){
    return FakePhoneVerificationController(ref);
 }))
```
